version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # porta do broker (AMQP)
      - "15672:15672" # porta do painel web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  app-producer:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mongodb
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - mongo
      - rabbitmq
  app-consumer:
    build:
      context: ../app-consumer
    env_file:
      - ../app-consumer/.env
    ports:
      - "8081:8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - rabbitmq