spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/mongodb}
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

sendgrid:
  api-key: ${SENDGRID_API_KEY:}
