spring:
  data:
    mongodb:
      uri: ${MONGO_URL}
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
  config:
    activate:
      on-profile:
        active: prod