spring:
  data:
    mongodb:
      uri: ${MONGO_URL}
      database: ${MONGO_DB_NAME:notificationdb}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    virtual-host: ${RABBITMQ_VHOST}
    ssl:
      enabled: true
  config:
    activate:
      on-profile:
        active: prod