spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/}
      database: ${MONGO_DB_NAME:notificationdb}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

dd:
  trace:
    enabled: true
  service:
    name: app-producer
  env: dev
  version: 1.0.0

management:
  metrics:
    export:
      datadog:
        api-key: ${DD_API_KEY}
        step: 30s
        uri: https://api.datadoghq.com